[package]
authors = ["kizkoh"]
name = "rapier"
version = "0.1.0"

[dependencies]
chrono = "0.4.0"
notify-rust = "3.4.2"
serde = "1.0.11"
serde_derive = "1.0.11"
serde_json = "1.0.2"

[dependencies.github-rs]
optional = false
path = "/home/kizkoh/repo/github/rapier/github-rs"
